### ISSUE TITLE
apply call functions not properly recorded

### ISSUE THREAD

**Issue by aaronrudkin** [aaronrudkin/werner#10]
I believe that calls from one function to another via a *apply function are not being recorded, possibly because the function is resolving as a symbol rather than a language call, so it's not being picked up?

**Comment by nfultz** [comment]
Ooff. This one will be hard because lapply drops in to C - you may need to
special case it. For functions that take functions, you may need a more
flexible data structure than an adjacency matrix.

**Comment by aaronrudkin** [comment]
I don't actually run any code; I just recursively process the source. As a result, I was thinking about doing it by waiting until the current processing hits a *apply call, and then extracting the second argument as though it were a function. In addition, I currently don't care about anonymous or (not sure the proper name in R) inner functions, so if it ends up being something of the format `vapply(junk_data, function(x) { x^3 + 1 }, numeric(1))` I don't really care. I just want to make sure I'm intercepting `vapply(junk_data, some_other_package_function, numeric(1))` calls -- and I should be reasonably able to do so.

**Comment by nfultz** [comment]
In that case , you should be able to use match.fun to resolve the symbol to
a function (or not), and use that predicate to fill out the adjacency
matrix.

**Comment by aaronrudkin** [comment]
`match.fun` didn't work for me (not sure what context I needed that I'm missing) but `getAnywhere` worked okay -- there are still a few weird issues but it solved the ones I was thinking of.
