### ISSUE TITLE
testthat environment fails when normal package use doesn't

### ISSUE THREAD

**Issue by aaronrudkin** [aaronrudkin/werner#2]
MWE:
```
library(werner)
explore_package("foreign")
```

Not super clear why this works but testthat's version doesn't; I'm guessing I need to add any packages that are tested into "Suggests".

**Comment by aaronrudkin** [comment]
[Hadley notes](http://r-pkgs.had.co.nz/check.html) that `R CMD CHECK` will fail if tests included unmet dependencies, which I take to mean that I need to soft-depend on anything I want to test on. Not ideal considering that some of my edge cases rely on external packages that I do not want users to depend on. Removed external packages for now, but need to come back to this later.

**Comment by nfultz** [comment]
Theres a skip if not installed helper function in testthat.
